dbname: bills_db
username: Joel
us_bills_subset: 500
ny_bills_subset: 500

subjects:
  - Health
  - Taxation
  - Bankruptcy
  - Competition and antitrust
  - Bank accounts, deposits, capital
  - Employee benefits and pensions
  - Intellectual property
  - Labor and employment
  - Securities

pipe_feats:
  - tf_title
  - tf_text
  - tfidf_title
  - tfidf_text
  # - lda_title
  # - lda_text

# model_type : logistic_regression
model_type: svc

logistic_regression:
  - C:
      - 10
      - 100
      - 1000000000
  - penalty:
      - l1

naive_bayes:
  - alpha:
      - 1

svc:
  - C:
      - 1

tf_text:
  - ngram_range:
      - !!python/tuple [1, 2]
  - min_df:
      - 10
  - max_df:
      - 0.4

tf_title:
  - ngram_range:
      - !!python/tuple [1, 3]
  - min_df:
      - 10
  - max_df:
      - 0.4

tfidf_text:
  - ngram_range:
      - !!python/tuple [1, 2]
  - min_df:
      - 10
  - max_df:
      - 0.4
  - max_features:
      - !!python/none

tfidf_title:
  - ngram_range:
      - !!python/tuple [1, 3]
  - min_df:
      - 10
  - max_df:
      - 0.4
  - max_features:
      - !!python/none

lda_model_text:
  - n_topics:
      - 100
      - 10

lda_tf_text:
  - ngram_range:
      - !!python/tuple [1, 1]
  - min_df:
      - 10
  - max_df:
      - 0.4

scoring: roc_auc
verbose: 10
folds: 3
# folds : 2
model_dir: /Users/Joel/Desktop/Insight/bill_taxonomy/models/
save_model: False
also_save_data: False
store_us: False
store_ny: False
njobs: 1
fig_dir: /Users/Joel/Desktop/Insight/presentations/figures/
score_column: svc
# dbwrite_host : localhost
dbwrite_host: ec2-52-45-31-100.compute-1.amazonaws.com
# dbwrite_user : Joel
dbwrite_user: ubuntu
