version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/code/logs

  db-init:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./logs:/code/logs
      - ${AWS_MOUNT:-}

volumes:
  postgres_data:
